server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/R-JAC0BS/MicroService_Aula
          search-paths:
          - microservices-java/configs/{application}
         
